// <auto-generated />
using System;
using DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataContext.Migrations
{
    [DbContext(typeof(AppDataContext))]
    [Migration("20220312180244_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("DbEntities.DbImport", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("DateCreatedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Filename")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("ProcessingEndUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("ProcessingStartUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("ProjectId");

                    b.ToTable("Imports");
                });

            modelBuilder.Entity("DbEntities.DbOrganization", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("DateCreatedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsHost")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Organizations");
                });

            modelBuilder.Entity("DbEntities.DbPage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("DateCreatedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Index")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SheetNameSuffix")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("SheetNumberSuffix")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("ProjectId");

                    b.ToTable("Pages");
                });

            modelBuilder.Entity("DbEntities.DbProject", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTimeOffset>("DateCreatedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("DesignerLockedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("EstimatedSquareFeet")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "Name")
                        .IsUnique();

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("FriendlyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Xml")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DataProtectionKeys");
                });

            modelBuilder.Entity("DbEntities.DbImport", b =>
                {
                    b.HasOne("DbEntities.DbOrganization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DbEntities.DbProject", "Project")
                        .WithMany("Imports")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("DbEntities.ValueObjects.DbFileRef", "File", b1 =>
                        {
                            b1.Property<Guid>("DbImportId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("FileId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("FileType")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("nvarchar(32)");

                            b1.HasKey("DbImportId");

                            b1.ToTable("Imports");

                            b1.WithOwner()
                                .HasForeignKey("DbImportId");
                        });

                    b.OwnsOne("ValueObjects.Percentage", "PercentComplete", b1 =>
                        {
                            b1.Property<Guid>("DbImportId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Value")
                                .HasColumnType("decimal(18,4)");

                            b1.HasKey("DbImportId");

                            b1.ToTable("Imports");

                            b1.WithOwner()
                                .HasForeignKey("DbImportId");
                        });

                    b.Navigation("File")
                        .IsRequired();

                    b.Navigation("Organization");

                    b.Navigation("PercentComplete")
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("DbEntities.DbOrganization", b =>
                {
                    b.OwnsOne("ValueObjects.OrganizationShortName", "ShortName", b1 =>
                        {
                            b1.Property<Guid>("DbOrganizationId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(16)
                                .HasColumnType("nvarchar(16)");

                            b1.HasKey("DbOrganizationId");

                            b1.HasIndex("Value")
                                .IsUnique();

                            b1.ToTable("Organizations");

                            b1.WithOwner()
                                .HasForeignKey("DbOrganizationId");
                        });

                    b.Navigation("ShortName")
                        .IsRequired();
                });

            modelBuilder.Entity("DbEntities.DbPage", b =>
                {
                    b.HasOne("DbEntities.DbOrganization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DbEntities.DbProject", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("DbEntities.ValueObjects.DbFileRef", "Pdf", b1 =>
                        {
                            b1.Property<Guid>("DbPageId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("FileId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("FileType")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("nvarchar(32)");

                            b1.HasKey("DbPageId");

                            b1.ToTable("Pages");

                            b1.WithOwner()
                                .HasForeignKey("DbPageId");
                        });

                    b.OwnsOne("DbEntities.ValueObjects.DbFileRef", "Thumbnail", b1 =>
                        {
                            b1.Property<Guid>("DbPageId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("FileId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("FileType")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("nvarchar(32)");

                            b1.HasKey("DbPageId");

                            b1.ToTable("Pages");

                            b1.WithOwner()
                                .HasForeignKey("DbPageId");
                        });

                    b.Navigation("Organization");

                    b.Navigation("Pdf")
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("Thumbnail")
                        .IsRequired();
                });

            modelBuilder.Entity("DbEntities.DbProject", b =>
                {
                    b.HasOne("DbEntities.DbOrganization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("DbEntities.ValueObjects.DbFileRef", "Photo", b1 =>
                        {
                            b1.Property<Guid>("DbProjectId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("FileId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("FileType")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("nvarchar(32)");

                            b1.HasKey("DbProjectId");

                            b1.ToTable("Projects");

                            b1.WithOwner()
                                .HasForeignKey("DbProjectId");
                        });

                    b.OwnsOne("DbEntities.ValueObjects.DbProjectReportOptions", "ReportOptions", b1 =>
                        {
                            b1.Property<Guid>("DbProjectId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("CompassAngle")
                                .HasColumnType("int");

                            b1.Property<bool>("IncludeCompassInFooter")
                                .HasColumnType("bit");

                            b1.Property<string>("PreparerName")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("SigneeName")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<int>("TitleBlockSheetNameFontSize")
                                .HasColumnType("int");

                            b1.HasKey("DbProjectId");

                            b1.ToTable("Projects");

                            b1.WithOwner()
                                .HasForeignKey("DbProjectId");

                            b1.OwnsOne("ValueObjects.CompanyContactInfo", "CompanyContactInfo", b2 =>
                                {
                                    b2.Property<Guid>("DbProjectReportOptionsDbProjectId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<string>("Name")
                                        .IsRequired()
                                        .HasMaxLength(128)
                                        .HasColumnType("nvarchar(128)");

                                    b2.HasKey("DbProjectReportOptionsDbProjectId");

                                    b2.ToTable("Projects");

                                    b2.WithOwner()
                                        .HasForeignKey("DbProjectReportOptionsDbProjectId");

                                    b2.OwnsOne("ValueObjects.EmailAddress", "Email", b3 =>
                                        {
                                            b3.Property<Guid>("CompanyContactInfoDbProjectReportOptionsDbProjectId")
                                                .HasColumnType("uniqueidentifier");

                                            b3.Property<string>("Value")
                                                .IsRequired()
                                                .HasMaxLength(128)
                                                .HasColumnType("nvarchar(128)");

                                            b3.HasKey("CompanyContactInfoDbProjectReportOptionsDbProjectId");

                                            b3.ToTable("Projects");

                                            b3.WithOwner()
                                                .HasForeignKey("CompanyContactInfoDbProjectReportOptionsDbProjectId");
                                        });

                                    b2.OwnsOne("ValueObjects.PhoneNumber", "Phone", b3 =>
                                        {
                                            b3.Property<Guid>("CompanyContactInfoDbProjectReportOptionsDbProjectId")
                                                .HasColumnType("uniqueidentifier");

                                            b3.Property<string>("Value")
                                                .IsRequired()
                                                .HasMaxLength(16)
                                                .HasColumnType("nvarchar(16)");

                                            b3.HasKey("CompanyContactInfoDbProjectReportOptionsDbProjectId");

                                            b3.ToTable("Projects");

                                            b3.WithOwner()
                                                .HasForeignKey("CompanyContactInfoDbProjectReportOptionsDbProjectId");
                                        });

                                    b2.OwnsOne("ValueObjects.Url", "Url", b3 =>
                                        {
                                            b3.Property<Guid>("CompanyContactInfoDbProjectReportOptionsDbProjectId")
                                                .HasColumnType("uniqueidentifier");

                                            b3.Property<string>("Value")
                                                .IsRequired()
                                                .HasColumnType("nvarchar(max)");

                                            b3.HasKey("CompanyContactInfoDbProjectReportOptionsDbProjectId");

                                            b3.ToTable("Projects");

                                            b3.WithOwner()
                                                .HasForeignKey("CompanyContactInfoDbProjectReportOptionsDbProjectId");
                                        });

                                    b2.Navigation("Email")
                                        .IsRequired();

                                    b2.Navigation("Phone")
                                        .IsRequired();

                                    b2.Navigation("Url")
                                        .IsRequired();
                                });

                            b1.Navigation("CompanyContactInfo");
                        });

                    b.OwnsOne("ValueObjects.PartialAddress", "Address", b1 =>
                        {
                            b1.Property<Guid>("DbProjectId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("City")
                                .HasMaxLength(64)
                                .HasColumnType("nvarchar(64)");

                            b1.Property<bool?>("HasValue")
                                .HasColumnType("bit");

                            b1.Property<string>("Line1")
                                .HasMaxLength(64)
                                .HasColumnType("nvarchar(64)");

                            b1.Property<string>("Line2")
                                .HasMaxLength(64)
                                .HasColumnType("nvarchar(64)");

                            b1.Property<string>("State")
                                .HasMaxLength(16)
                                .HasColumnType("nvarchar(16)");

                            b1.HasKey("DbProjectId");

                            b1.ToTable("Projects");

                            b1.WithOwner()
                                .HasForeignKey("DbProjectId");

                            b1.OwnsOne("ValueObjects.PostalCode", "PostalCode", b2 =>
                                {
                                    b2.Property<Guid>("PartialAddressDbProjectId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<string>("Value")
                                        .IsRequired()
                                        .HasMaxLength(16)
                                        .HasColumnType("nvarchar(16)");

                                    b2.HasKey("PartialAddressDbProjectId");

                                    b2.ToTable("Projects");

                                    b2.WithOwner()
                                        .HasForeignKey("PartialAddressDbProjectId");
                                });

                            b1.Navigation("PostalCode");
                        });

                    b.OwnsOne("ValueObjects.ProjectBudgetOptions", "BudgetOptions", b1 =>
                        {
                            b1.Property<Guid>("DbProjectId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<bool>("ShowPricePerSquareFoot")
                                .HasColumnType("bit");

                            b1.Property<bool>("ShowPricingInBudgetBreakdown")
                                .HasColumnType("bit");

                            b1.HasKey("DbProjectId");

                            b1.ToTable("Projects");

                            b1.WithOwner()
                                .HasForeignKey("DbProjectId");

                            b1.OwnsOne("ValueObjects.Percentage", "CostAdjustment", b2 =>
                                {
                                    b2.Property<Guid>("ProjectBudgetOptionsDbProjectId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<decimal>("Value")
                                        .HasColumnType("decimal(18,4)");

                                    b2.HasKey("ProjectBudgetOptionsDbProjectId");

                                    b2.ToTable("Projects");

                                    b2.WithOwner()
                                        .HasForeignKey("ProjectBudgetOptionsDbProjectId");
                                });

                            b1.OwnsOne("ValueObjects.Percentage", "DepositPercentage", b2 =>
                                {
                                    b2.Property<Guid>("ProjectBudgetOptionsDbProjectId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<decimal>("Value")
                                        .HasColumnType("decimal(18,4)");

                                    b2.HasKey("ProjectBudgetOptionsDbProjectId");

                                    b2.ToTable("Projects");

                                    b2.WithOwner()
                                        .HasForeignKey("ProjectBudgetOptionsDbProjectId");
                                });

                            b1.Navigation("CostAdjustment")
                                .IsRequired();

                            b1.Navigation("DepositPercentage")
                                .IsRequired();
                        });

                    b.Navigation("Address")
                        .IsRequired();

                    b.Navigation("BudgetOptions")
                        .IsRequired();

                    b.Navigation("Organization");

                    b.Navigation("Photo");

                    b.Navigation("ReportOptions")
                        .IsRequired();
                });

            modelBuilder.Entity("DbEntities.DbProject", b =>
                {
                    b.Navigation("Imports");
                });
#pragma warning restore 612, 618
        }
    }
}
