// <auto-generated />
using System;
using DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataContext.Migrations
{
    [DbContext(typeof(AppDataContext))]
    [Migration("20211020210445_AddProject")]
    partial class AddProject
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DbEntities.DbDeletedFile", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<Guid>("FileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.ToTable("DeletedFiles");
                });

            modelBuilder.Entity("DbEntities.DbOrganization", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("DateCreatedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsHost")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Organizations");
                });

            modelBuilder.Entity("DbEntities.DbPage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("DateCreatedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PdfFileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ThumbnailFileId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.ToTable("Pages");
                });

            modelBuilder.Entity("DbEntities.DbProject", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("DateCreatedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EstimatedSquareFeet")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("DbEntities.DbSymbol", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("DateCreatedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SvgText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.ToTable("Symbols");
                });

            modelBuilder.Entity("DbEntities.DbUser", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("DateCreatedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ITI.DDD.Logging.LogEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Exception")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Hostname")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Level")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Process")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Thread")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("UserId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("UserName")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTimeOffset>("WhenUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("WhenUtc");

                    b.ToTable("LogEntries");
                });

            modelBuilder.Entity("DbEntities.DbOrganization", b =>
                {
                    b.OwnsOne("ValueObjects.OrganizationShortName", "ShortName", b1 =>
                        {
                            b1.Property<Guid>("DbOrganizationId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<bool?>("HasValue")
                                .HasColumnType("bit");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(16)
                                .HasColumnType("nvarchar(16)");

                            b1.HasKey("DbOrganizationId");

                            b1.HasIndex("Value")
                                .IsUnique()
                                .HasFilter("[ShortName_Value] IS NOT NULL");

                            b1.ToTable("Organizations");

                            b1.WithOwner()
                                .HasForeignKey("DbOrganizationId");
                        });

                    b.Navigation("ShortName");
                });

            modelBuilder.Entity("DbEntities.DbPage", b =>
                {
                    b.HasOne("DbEntities.DbOrganization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("DbEntities.DbProject", b =>
                {
                    b.HasOne("DbEntities.DbOrganization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("DbEntities.ValueObjects.DbFileRef", "Photo", b1 =>
                        {
                            b1.Property<Guid>("DbProjectId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("FileId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("FileType")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<bool?>("HasValue")
                                .HasColumnType("bit");

                            b1.HasKey("DbProjectId");

                            b1.ToTable("Projects");

                            b1.WithOwner()
                                .HasForeignKey("DbProjectId");
                        });

                    b.OwnsOne("ValueObjects.PartialAddress", "Address", b1 =>
                        {
                            b1.Property<Guid>("DbProjectId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("nvarchar(64)");

                            b1.Property<bool?>("HasValue")
                                .HasColumnType("bit");

                            b1.Property<string>("Line1")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("nvarchar(64)");

                            b1.Property<string>("Line2")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("nvarchar(64)");

                            b1.Property<string>("State")
                                .IsRequired()
                                .HasMaxLength(16)
                                .HasColumnType("nvarchar(16)");

                            b1.HasKey("DbProjectId");

                            b1.ToTable("Projects");

                            b1.WithOwner()
                                .HasForeignKey("DbProjectId");

                            b1.OwnsOne("ValueObjects.PostalCode", "PostalCode", b2 =>
                                {
                                    b2.Property<Guid>("PartialAddressDbProjectId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<bool?>("HasValue")
                                        .HasColumnType("bit");

                                    b2.Property<string>("Value")
                                        .IsRequired()
                                        .HasMaxLength(16)
                                        .HasColumnType("nvarchar(16)");

                                    b2.HasKey("PartialAddressDbProjectId");

                                    b2.ToTable("Projects");

                                    b2.WithOwner()
                                        .HasForeignKey("PartialAddressDbProjectId");
                                });

                            b1.Navigation("PostalCode")
                                .IsRequired();
                        });

                    b.OwnsOne("ValueObjects.ProjectBudgetOptions", "BudgetOptions", b1 =>
                        {
                            b1.Property<Guid>("DbProjectId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<bool?>("HasValue")
                                .HasColumnType("bit");

                            b1.Property<bool>("ShowPricePerSquareFoot")
                                .HasColumnType("bit");

                            b1.Property<bool>("ShowPricingInBudgetBreakdown")
                                .HasColumnType("bit");

                            b1.HasKey("DbProjectId");

                            b1.ToTable("Projects");

                            b1.WithOwner()
                                .HasForeignKey("DbProjectId");

                            b1.OwnsOne("ValueObjects.Percentage", "CostAdjustment", b2 =>
                                {
                                    b2.Property<Guid>("ProjectBudgetOptionsDbProjectId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<bool?>("HasValue")
                                        .HasColumnType("bit");

                                    b2.Property<decimal>("Value")
                                        .HasColumnType("decimal(18,4)");

                                    b2.HasKey("ProjectBudgetOptionsDbProjectId");

                                    b2.ToTable("Projects");

                                    b2.WithOwner()
                                        .HasForeignKey("ProjectBudgetOptionsDbProjectId");
                                });

                            b1.OwnsOne("ValueObjects.Percentage", "DepositPercentage", b2 =>
                                {
                                    b2.Property<Guid>("ProjectBudgetOptionsDbProjectId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<bool?>("HasValue")
                                        .HasColumnType("bit");

                                    b2.Property<decimal>("Value")
                                        .HasColumnType("decimal(18,4)");

                                    b2.HasKey("ProjectBudgetOptionsDbProjectId");

                                    b2.ToTable("Projects");

                                    b2.WithOwner()
                                        .HasForeignKey("ProjectBudgetOptionsDbProjectId");
                                });

                            b1.Navigation("CostAdjustment")
                                .IsRequired();

                            b1.Navigation("DepositPercentage")
                                .IsRequired();
                        });

                    b.OwnsOne("ValueObjects.ProjectReportOptions", "ReportOptions", b1 =>
                        {
                            b1.Property<Guid>("DbProjectId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("CompassAngle")
                                .HasColumnType("int");

                            b1.Property<bool?>("HasValue")
                                .HasColumnType("bit");

                            b1.Property<bool>("IncludeCompassInFooter")
                                .HasColumnType("bit");

                            b1.Property<string>("PreparerName")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("SigneeName")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<int>("TitleBlockSheetNameFontSize")
                                .HasColumnType("int");

                            b1.HasKey("DbProjectId");

                            b1.ToTable("Projects");

                            b1.WithOwner()
                                .HasForeignKey("DbProjectId");
                        });

                    b.Navigation("Address")
                        .IsRequired();

                    b.Navigation("BudgetOptions")
                        .IsRequired();

                    b.Navigation("Organization");

                    b.Navigation("Photo");

                    b.Navigation("ReportOptions")
                        .IsRequired();
                });

            modelBuilder.Entity("DbEntities.DbSymbol", b =>
                {
                    b.HasOne("DbEntities.DbOrganization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("DbEntities.DbUser", b =>
                {
                    b.HasOne("DbEntities.DbOrganization", "Organization")
                        .WithMany("Users")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("ITI.Baseline.Passwords.EncodedPassword", "EncodedPassword", b1 =>
                        {
                            b1.Property<Guid>("DbUserId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<bool?>("HasValue")
                                .HasColumnType("bit");

                            b1.Property<string>("Value")
                                .HasMaxLength(128)
                                .HasColumnType("nvarchar(128)");

                            b1.HasKey("DbUserId");

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("DbUserId");
                        });

                    b.OwnsOne("ITI.Baseline.ValueObjects.EmailAddress", "Email", b1 =>
                        {
                            b1.Property<Guid>("DbUserId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<bool?>("HasValue")
                                .HasColumnType("bit");

                            b1.Property<string>("Value")
                                .HasMaxLength(256)
                                .HasColumnType("nvarchar(256)");

                            b1.HasKey("DbUserId");

                            b1.HasIndex("Value")
                                .IsUnique()
                                .HasFilter("[Email_Value] IS NOT NULL");

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("DbUserId");
                        });

                    b.OwnsOne("ValueObjects.PersonName", "Name", b1 =>
                        {
                            b1.Property<Guid>("DbUserId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("First")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("nvarchar(64)");

                            b1.Property<bool?>("HasValue")
                                .HasColumnType("bit");

                            b1.Property<string>("Last")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("nvarchar(64)");

                            b1.HasKey("DbUserId");

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("DbUserId");
                        });

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("EncodedPassword");

                    b.Navigation("Name")
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("DbEntities.DbOrganization", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
